= Unblu Visitor Single Sign-On (SSO)
:source-highlighter: rouge
//:toc:


A sample application to pass the identity properties of the user into a cross origin Unblu backend using a signed and encrypted Json Web Token (JWT).

1. After the login this app calls `POST https://unblu.example.com/rest/v3/authenticator/loginWithSecureToken`
with the signed JWT in the request body.
2. Unblu will then download the Json Web Key (JWK) used to sign the JWT from this sample app (i.e. https://onlinebanking.example.com/api/jwk).
3. Assuming the JWT is valid, Unblu sets a session id as a cookie on `unblu.example.com`.

Unblu now uses the JWT in the cookie as the authentication.

NOTE: Login using a JWT is only possible since Unblu 6.13.0!

CAUTION: The Unblu backend and the host application must run on the same second-level domain (e.g. `example.com`).
Otherwise, some browsers (i.e. Safari) will treat the Unblu authentication cookie as a third-party cookie and therefore block it.

== Configuration

.Change `application.properties` to reconfigure this Sample App
[source,ini]
----
include::src/main/resources/application.properties[tag=config]
----

== Unblu Backend

The configuration `unblu.baseUrl` needs to point to a running Unblu installation with enabled ID propagation based on JWT.

.JWT Configuration in Unblu
[source,ini]
----
com.unblu.identifier.restrictedPathPrefix=co-${systemIdentifier}

com.unblu.authentication.untrusted.sources=LOCAL

com.unblu.authentication.jwt.jwkUrl=https://onlinebanking.example.com/api/jwk
com.unblu.authentication.jwt.expectedIssuer=https://onlinebanking.example.com
com.unblu.authentication.jwt.expectedAudience=https://unblu.example.com
com.unblu.authentication.jwt.useEncryption=false
com.unblu.authentication.jwt.encryptionKey=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpt4w09CoBF4UQ\n2YTr9n1LjJZjIvnjeE7UoGwJrxEFxUhTMaRY7To3iYMxH6NaUwwABSt4rbykeZFB\nvus4oRBVqcisBXzP8+USX9u1cuhteNGqvXpVsw0YeuhIYiYTTkzAcFHTi/pJDrdd\npOVMnpCKtO++oec7ILhOOSxrxoBjFg4ICdJIz+fkGB0hxez/Xp6xNp2sfEv5ULhj\nxjvXXXjg6vD0u3BCt+BxRhpRpPRwbPmwGeWY/sjPttBXhPKIBIchRqRfRHOz3MJJ\nnQonRItxkwbWgIvgZ2fCyIDiKKyYFxG0fSkSFChTuuMOD+6a3cISSTXAs/H7chy+\nL7f3EJp3AgMBAAECggEAKcaomJBRlps3ggJJGdw+003z5stBP6DppqUmcuvJAOai\n+veJQOqEHg+XX4wuJZmzpn2fScFaYhIak1hvhiz/XFbCsrVXF8ktZex6pJt4YxoO\nYjzp1BaS7qeybb7bKH1pnyUGv1ABd+JLeJ2SY93ULpCDQyWPSZqwQ3EHYjAmgj0Q\nzWnxNAwqz8hKkHvNimSZmZFPqAA6IOeoRJY/yBPjl/CTbivaIoHnPCs1bGJ6wtoX\nmQVEv8UrEUITj/W3pSWIWpYjSkxLIAH6CrstusPIdESX9a2XmpEbMblKhM4TTYgz\nUu6KH8CVWqJEqL/EkoTv2Z+ZmprgNIJ/9XS26fgSIQKBgQDblu4MVn5zaKY0JPwE\nF0sLQ02vaRirfjtBsQpiuo7czmVz02I1xwnj/j8GNOGQxRdDPXblR19c0zmSQq4X\nfX3PYq+ZZv9OTU1gaEqx2BirNk/IifI0G8R9xdy7/KvFXA4cbMdrYyPbx6jy1e6S\nb0Hlb3JQFqHUinP6cMXuvqWUVQKBgQDF26RE7lxkGypmBgTIoC/zLkKqtB/9pWTq\n2yDVRFuoxTRgRLdb5c+6Vmyty4Pc846s8MAb2eA/5SzeU6kYcNTVUpPGmVDuG6P6\nyIvpIaKGieSo93kfFMuzizoolaARQxa4Cgt7D3F0rTXwzl86fdmmcz2tc+r4EEZ9\nVAELUfOfmwKBgAkvHdOsRmujQ9hId7XgF4ZoETa16Y86n1XXBr0sWk9H3pxiief/\n5B0CBDbJPWnlpFxulKtwOb/TIcRJP6jB2eIzmW6MDT+EIilXE1Cu3hFDG0Ei69tc\nEfLEtL+0CKcfe4Oa1RhbtCM8DYfihLDhMFtdNuW8nJYcGE+wKccbeCdlAoGAaQLE\n8azMrnjYjON+4HhcWqXfzjfhjr6cjCWXDHnGaBGaVcnCw2x6TryV27vbFYbS36i7\nXUzKvz7EDI+8fHNOEpZMRiiTEnzrECwmTaqDVwKSsLb/uuZPotAvIuEe3mqMAUub\ngknU/ob7zP3K/wFSZgxd3NRcDiKdNuFB2J87PScCgYEAgwC7RkLO1IYS+FZ0aHLL\nrkbEqT5CHtnf2eLW6xLYhxHFFacpbhLVOAs6bXT5NWkm4UmgZTBEAwxtJ+EjXMOn\nLQJXTsDYrWTWzyShBCfID+6kT5/JLGK06CmAnOXadd2ESY3d+QdKE0jE1cbTp2Q8\nIIQdfNOVVaTOS+OHMuwNraA=\n-----END PRIVATE KEY-----

com.unblu.authentication.tokenSignup.enabled=true
com.unblu.authentication.tokenSignup.claimMapping.username=email
com.unblu.authentication.tokenSignup.claimMapping.email=email
com.unblu.authentication.tokenSignup.claimMapping.firstName=firstName
com.unblu.authentication.tokenSignup.claimMapping.lastName=lastName
----

.Generate RSA key pair
[source,bash]
----
openssl genpkey -algorithm RSA -out unblu.pem -pkeyopt rsa_keygen_bits:2048
openssl rsa -pubout -in unblu.pem -out unblu_public.pem
----

.Key pair for testing
[source]
----
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqbeMNPQqAReFENmE6/Z9
S4yWYyL543hO1KBsCa8RBcVIUzGkWO06N4mDMR+jWlMMAAUreK28pHmRQb7rOKEQ
VanIrAV8z/PlEl/btXLobXjRqr16VbMNGHroSGImE05MwHBR04v6SQ63XaTlTJ6Q
irTvvqHnOyC4Tjksa8aAYxYOCAnSSM/n5BgdIcXs/16esTadrHxL+VC4Y8Y71114
4Orw9LtwQrfgcUYaUaT0cGz5sBnlmP7Iz7bQV4TyiASHIUakX0Rzs9zCSZ0KJ0SL
cZMG1oCL4GdnwsiA4iismBcRtH0pEhQoU7rjDg/umt3CEkk1wLPx+3Icvi+39xCa
dwIDAQAB
-----END PUBLIC KEY-----

-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpt4w09CoBF4UQ
2YTr9n1LjJZjIvnjeE7UoGwJrxEFxUhTMaRY7To3iYMxH6NaUwwABSt4rbykeZFB
vus4oRBVqcisBXzP8+USX9u1cuhteNGqvXpVsw0YeuhIYiYTTkzAcFHTi/pJDrdd
pOVMnpCKtO++oec7ILhOOSxrxoBjFg4ICdJIz+fkGB0hxez/Xp6xNp2sfEv5ULhj
xjvXXXjg6vD0u3BCt+BxRhpRpPRwbPmwGeWY/sjPttBXhPKIBIchRqRfRHOz3MJJ
nQonRItxkwbWgIvgZ2fCyIDiKKyYFxG0fSkSFChTuuMOD+6a3cISSTXAs/H7chy+
L7f3EJp3AgMBAAECggEAKcaomJBRlps3ggJJGdw+003z5stBP6DppqUmcuvJAOai
+veJQOqEHg+XX4wuJZmzpn2fScFaYhIak1hvhiz/XFbCsrVXF8ktZex6pJt4YxoO
Yjzp1BaS7qeybb7bKH1pnyUGv1ABd+JLeJ2SY93ULpCDQyWPSZqwQ3EHYjAmgj0Q
zWnxNAwqz8hKkHvNimSZmZFPqAA6IOeoRJY/yBPjl/CTbivaIoHnPCs1bGJ6wtoX
mQVEv8UrEUITj/W3pSWIWpYjSkxLIAH6CrstusPIdESX9a2XmpEbMblKhM4TTYgz
Uu6KH8CVWqJEqL/EkoTv2Z+ZmprgNIJ/9XS26fgSIQKBgQDblu4MVn5zaKY0JPwE
F0sLQ02vaRirfjtBsQpiuo7czmVz02I1xwnj/j8GNOGQxRdDPXblR19c0zmSQq4X
fX3PYq+ZZv9OTU1gaEqx2BirNk/IifI0G8R9xdy7/KvFXA4cbMdrYyPbx6jy1e6S
b0Hlb3JQFqHUinP6cMXuvqWUVQKBgQDF26RE7lxkGypmBgTIoC/zLkKqtB/9pWTq
2yDVRFuoxTRgRLdb5c+6Vmyty4Pc846s8MAb2eA/5SzeU6kYcNTVUpPGmVDuG6P6
yIvpIaKGieSo93kfFMuzizoolaARQxa4Cgt7D3F0rTXwzl86fdmmcz2tc+r4EEZ9
VAELUfOfmwKBgAkvHdOsRmujQ9hId7XgF4ZoETa16Y86n1XXBr0sWk9H3pxiief/
5B0CBDbJPWnlpFxulKtwOb/TIcRJP6jB2eIzmW6MDT+EIilXE1Cu3hFDG0Ei69tc
EfLEtL+0CKcfe4Oa1RhbtCM8DYfihLDhMFtdNuW8nJYcGE+wKccbeCdlAoGAaQLE
8azMrnjYjON+4HhcWqXfzjfhjr6cjCWXDHnGaBGaVcnCw2x6TryV27vbFYbS36i7
XUzKvz7EDI+8fHNOEpZMRiiTEnzrECwmTaqDVwKSsLb/uuZPotAvIuEe3mqMAUub
gknU/ob7zP3K/wFSZgxd3NRcDiKdNuFB2J87PScCgYEAgwC7RkLO1IYS+FZ0aHLL
rkbEqT5CHtnf2eLW6xLYhxHFFacpbhLVOAs6bXT5NWkm4UmgZTBEAwxtJ+EjXMOn
LQJXTsDYrWTWzyShBCfID+6kT5/JLGK06CmAnOXadd2ESY3d+QdKE0jE1cbTp2Q8
IIQdfNOVVaTOS+OHMuwNraA=
-----END PRIVATE KEY-----

----


