= Unblu visitor single sign-on (SSO)
:source-highlighter: rouge

Be sure to review our https://unblu.github.io/unblu-visitor-sso-sample/[visitor SSO implementation tutorial] as well.

== Running the sample application

First, build the sample application from source:

.Build from source
[source,bash]
----
./gradlew bootRun
----

The following command runs the sample application on port 8080 in a Docker container:

.Run using Docker
[source,bash]
----
docker run --rm -p 8080:8080 ghcr.io/unblu/unblu-visitor-sso-sample
----

Then open http://localhost:8080.

.cURL samples
[source,bash]
----
# List generated JWKs
curl -s localhost:8080/api/jwk | jq
# Issue a new JWT
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{"username": "pmuster", "email": "peter.muster@example.com", "firstname": "Peter", "lastname": "Muster"}' \
  localhost:8080/api/token | jq
----

== Configuration

The sample application's configuration property `unblu.serverUrl` must point to a running Unblu installation.
JWT based visitor SSO must be enabled on the Unblu server.

.Change `src/main/resources/application.properties` to reconfigure the sample application
[source,ini]
----
include::src/main/resources/application.properties[tag=config]
----

== Key pair for testing

.Public key
[source]
----
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqbeMNPQqAReFENmE6/Z9
S4yWYyL543hO1KBsCa8RBcVIUzGkWO06N4mDMR+jWlMMAAUreK28pHmRQb7rOKEQ
VanIrAV8z/PlEl/btXLobXjRqr16VbMNGHroSGImE05MwHBR04v6SQ63XaTlTJ6Q
irTvvqHnOyC4Tjksa8aAYxYOCAnSSM/n5BgdIcXs/16esTadrHxL+VC4Y8Y71114
4Orw9LtwQrfgcUYaUaT0cGz5sBnlmP7Iz7bQV4TyiASHIUakX0Rzs9zCSZ0KJ0SL
cZMG1oCL4GdnwsiA4iismBcRtH0pEhQoU7rjDg/umt3CEkk1wLPx+3Icvi+39xCa
dwIDAQAB
-----END PUBLIC KEY-----
----

.Private key
[source]
----
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpt4w09CoBF4UQ
2YTr9n1LjJZjIvnjeE7UoGwJrxEFxUhTMaRY7To3iYMxH6NaUwwABSt4rbykeZFB
vus4oRBVqcisBXzP8+USX9u1cuhteNGqvXpVsw0YeuhIYiYTTkzAcFHTi/pJDrdd
pOVMnpCKtO++oec7ILhOOSxrxoBjFg4ICdJIz+fkGB0hxez/Xp6xNp2sfEv5ULhj
xjvXXXjg6vD0u3BCt+BxRhpRpPRwbPmwGeWY/sjPttBXhPKIBIchRqRfRHOz3MJJ
nQonRItxkwbWgIvgZ2fCyIDiKKyYFxG0fSkSFChTuuMOD+6a3cISSTXAs/H7chy+
L7f3EJp3AgMBAAECggEAKcaomJBRlps3ggJJGdw+003z5stBP6DppqUmcuvJAOai
+veJQOqEHg+XX4wuJZmzpn2fScFaYhIak1hvhiz/XFbCsrVXF8ktZex6pJt4YxoO
Yjzp1BaS7qeybb7bKH1pnyUGv1ABd+JLeJ2SY93ULpCDQyWPSZqwQ3EHYjAmgj0Q
zWnxNAwqz8hKkHvNimSZmZFPqAA6IOeoRJY/yBPjl/CTbivaIoHnPCs1bGJ6wtoX
mQVEv8UrEUITj/W3pSWIWpYjSkxLIAH6CrstusPIdESX9a2XmpEbMblKhM4TTYgz
Uu6KH8CVWqJEqL/EkoTv2Z+ZmprgNIJ/9XS26fgSIQKBgQDblu4MVn5zaKY0JPwE
F0sLQ02vaRirfjtBsQpiuo7czmVz02I1xwnj/j8GNOGQxRdDPXblR19c0zmSQq4X
fX3PYq+ZZv9OTU1gaEqx2BirNk/IifI0G8R9xdy7/KvFXA4cbMdrYyPbx6jy1e6S
b0Hlb3JQFqHUinP6cMXuvqWUVQKBgQDF26RE7lxkGypmBgTIoC/zLkKqtB/9pWTq
2yDVRFuoxTRgRLdb5c+6Vmyty4Pc846s8MAb2eA/5SzeU6kYcNTVUpPGmVDuG6P6
yIvpIaKGieSo93kfFMuzizoolaARQxa4Cgt7D3F0rTXwzl86fdmmcz2tc+r4EEZ9
VAELUfOfmwKBgAkvHdOsRmujQ9hId7XgF4ZoETa16Y86n1XXBr0sWk9H3pxiief/
5B0CBDbJPWnlpFxulKtwOb/TIcRJP6jB2eIzmW6MDT+EIilXE1Cu3hFDG0Ei69tc
EfLEtL+0CKcfe4Oa1RhbtCM8DYfihLDhMFtdNuW8nJYcGE+wKccbeCdlAoGAaQLE
8azMrnjYjON+4HhcWqXfzjfhjr6cjCWXDHnGaBGaVcnCw2x6TryV27vbFYbS36i7
XUzKvz7EDI+8fHNOEpZMRiiTEnzrECwmTaqDVwKSsLb/uuZPotAvIuEe3mqMAUub
gknU/ob7zP3K/wFSZgxd3NRcDiKdNuFB2J87PScCgYEAgwC7RkLO1IYS+FZ0aHLL
rkbEqT5CHtnf2eLW6xLYhxHFFacpbhLVOAs6bXT5NWkm4UmgZTBEAwxtJ+EjXMOn
LQJXTsDYrWTWzyShBCfID+6kT5/JLGK06CmAnOXadd2ESY3d+QdKE0jE1cbTp2Q8
IIQdfNOVVaTOS+OHMuwNraA=
-----END PRIVATE KEY-----
----

== Known Issues

None