name: Build and publish application
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests with JDK 21 🧪
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Build with Java 21 and run tests
        run: ./gradlew clean build test --console=plain

  publish:
    name: Publish image to Github Container Registry 📦
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Build image
        if: github.ref == 'refs/heads/main'
        run: |
          ./gradlew --version
          ./gradlew jib \
            -Djib.to.tags=${GITHUB_SHA::8},latest \
            -Djib.to.auth.username=${{ github.repository_owner }} \
            -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }} \
            --console=plain
      - name: Build image (dry-run)
        if: github.ref != 'refs/heads/main'
        run: |
          ./gradlew jibDockerBuild --console=plain
